memberaudit/urls.py
from django.urls import path

from . import views

app_name = "memberaudit"

urlpatterns = [
    path("", views.index, name="index"),
    path("launcher", views.launcher, name="launcher"),
    path(
        "character_viewer/<int:character_pk>/",
        views.character_viewer,
        name="character_viewer",
    ),
    path("add_character", views.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        views.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        views.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        views.unshare_character,
        name="unshare_character",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        views.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        views.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        views.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        views.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        views.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        views.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        views.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        views.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        views.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail_data/<int:character_pk>/<int:mail_pk>/",
        views.character_mail_data,
        name="character_mail_data",
    ),
    path(
        "character_roles_data/<int:character_pk>/",
        views.character_roles_data,
        name="character_roles_data",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        views.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        views.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        views.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        views.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        views.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path("character_finder", views.character_finder, name="character_finder"),
    path(
        "character_finder_data",
        views.character_finder_data,
        name="character_finder_data",
    ),
    path("reports", views.reports, name="reports"),
    path(
        "user_compliance_report_data",
        views.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        views.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        views.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        views.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        views.character_attribute_data,
        name="character_attribute_data",
    ),
]

memberaudit/views/character_viewer.py
"""
views for character_viewer actions
"""

import datetime as dt
import humanize
from typing import Optional

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count, F, Max, Q, Sum
from django.db import models
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.html import format_html
from django.utils.timesince import timeuntil
from django.utils.timezone import now
from django.utils.translation import gettext
from eveuniverse.core import eveimageserver

from memberaudit import __title__
from memberaudit.constants import EVE_CATEGORY_ID_SHIP
from memberaudit.decorators import fetch_character_if_allowed
from memberaudit.helpers import eve_solar_system_to_html
from memberaudit.models import (
    Character,
    CharacterAsset,
    CharacterContract,
    CharacterContractItem,
    CharacterMail,
    Location,
)
from memberaudit.utils import (
    LoggerAddTag,
    add_bs_label_html,
    add_no_wrap_html,
    create_link_html,
    yesno_str,
)
from memberaudit.views.constants import (
    DEFAULT_ICON_SIZE,
    MAIL_LABEL_ID_ALL_MAILS,
    MAP_SKILL_LEVEL_ARABIC_TO_ROMAN,
    MY_DATETIME_FORMAT,
    SKILLQUEUE_DATETIME_FORMAT,
    SKILL_SET_DEFAULT_ICON_TYPE_ID,
    UNGROUPED_SKILL_SET,
)
from memberaudit.views.utils import (
    add_common_context,
    create_icon_plus_name_html,
    yesnonone_str,
)

from allianceauth.services.hooks import get_extension_logger

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


@login_required
@permission_required("memberaudit.basic_access")
@fetch_character_if_allowed(
    "details",
    "wallet_balance",
    "skillpoints",
    "character_ownership__user",
    "character_ownership__user__profile__main_character",
    "character_ownership__character",
    "location__location",
    "location__eve_solar_system",
    "location__eve_solar_system__eve_constellation__eve_region",
    "online_status",
)
def character_viewer(request, character_pk: int, character: Character) -> HttpResponse:
    """main view for showing a character with all details

    Args:
    - character_pk: PK for character to be shown

    GET Params:
    - tab: ID of tab to be shown  (optional)
    """
    # character details
    try:
        character_details = character.details
    except ObjectDoesNotExist:
        character_details = None

    # main character
    auth_character = character.character_ownership.character
    try:
        main_character = character.character_ownership.user.profile.main_character
        main = f"[{main_character.corporation_ticker}] {main_character.character_name}"
    except AttributeError:
        main_character = None
        main = "-"

    # mailing lists
    mailing_lists_qs = character.mailing_lists.all().annotate(
        unread_count=Count("recipient_mails", filter=Q(recipient_mails__is_read=False))
    )
    mailing_lists = [
        {
            "list_id": obj.id,
            "name_plus": obj.name_plus,
            "unread_count": obj.unread_count,
        }
        for obj in mailing_lists_qs
    ]

    # mail labels
    mail_labels = list(
        character.mail_labels.values(
            "label_id", "name", unread_count_2=F("unread_count")
        )
    )

    total_unread_count = sum(
        [obj["unread_count_2"] for obj in mail_labels if obj["unread_count_2"]]
    )
    total_unread_count += sum(
        [obj["unread_count"] for obj in mailing_lists if obj["unread_count"]]
    )

    mail_labels.append(
        {
            "label_id": MAIL_LABEL_ID_ALL_MAILS,
            "name": "All Mails",
            "unread_count_2": total_unread_count,
        }
    )

    # registered characters
    registered_characters = list(
        Character.objects.select_related(
            "character_ownership", "character_ownership__character"
        )
        .filter(character_ownership__user=character.character_ownership.user)
        .order_by("character_ownership__character__character_name")
        .values(
            "pk",
            "is_shared",
            name=F("character_ownership__character__character_name"),
            character_id=F("character_ownership__character__character_id"),
        )
    )

    # assets total value
    character_assets_total = (
        character.assets.exclude(is_blueprint_copy=True)
        .aggregate(
            total=Sum(
                F("quantity") * F("eve_type__market_price__average_price"),
                output_field=models.FloatField(),
            )
        )
        .get("total")
    )

    # implants
    try:
        has_implants = character.implants.count() > 0
    except ObjectDoesNotExist:
        has_implants = False

    # last updates
    try:
        last_updates = {
            obj["section"]: obj["finished_at"]
            for obj in character.update_status_set.filter(is_success=True).values(
                "section", "finished_at"
            )
        }
    except ObjectDoesNotExist:
        last_updates = None

    page_title = "Character Sheet"
    if not character.user_is_owner(request.user):
        page_title = format_html(
            '{}&nbsp;<i class="far fa-eye" title="You do not own this character"></i>',
            page_title,
        )

    context = {
        "page_title": page_title,
        "character": character,
        "auth_character": auth_character,
        "character_details": character_details,
        "mail_labels": mail_labels,
        "mailing_lists": mailing_lists,
        "main": main,
        "main_character_id": main_character.character_id if main_character else None,
        "registered_characters": registered_characters,
        "show_tab": request.GET.get("tab", ""),
        "last_updates": last_updates,
        "character_assets_total": character_assets_total,
        "has_implants": has_implants,
        "is_assets_updating": character.is_section_updating(
            Character.UpdateSection.ASSETS
        ),
    }
    return render(
        request,
        "memberaudit/character_viewer.html",
        add_common_context(request, context),
    )


@login_required
@permission_required("memberaudit.basic_access")
@fetch_character_if_allowed()
def character_assets_data(
    request, character_pk: int, character: Character
) -> JsonResponse:
    data = list()
    try:
        asset_qs = (
            character.assets.annotate_pricing()
            .select_related(
                "eve_type",
                "eve_type__eve_group",
                "eve_type__eve_group__eve_category",
                "location",
                "location__eve_solar_system__eve_constellation__eve_region",
            )
            .filter(location__isnull=False)
        )

    except ObjectDoesNotExist:
        return HttpResponseNotFound()

    assets_with_children_ids = set(
        character.assets.filter(children__isnull=False).values_list(
            "item_id", flat=True
        )
    )

    location_counts = {
        obj["id"]: obj["items_count"]
        for obj in (
            Location.objects.filter(characterasset__character=character)
            .annotate(items_count=Count("characterasset"))
            .values("id", "items_count")
        )
    }

    for asset in asset_qs:
        if asset.location.eve_solar_system:
            region = asset.location.eve_solar_system.eve_constellation.eve_region.name
            solar_system = asset.location.eve_solar_system.name
        else:
            region = ""
            solar_system = ""

        is_ship = yesno_str(
            asset.eve_type.eve_group.eve_category_id == EVE_CATEGORY_ID_SHIP
        )

        if asset.item_id in assets_with_children_ids:
            ajax_children_url = reverse(
                "memberaudit:character_asset_container",
                args=[character.pk, asset.pk],
            )
            actions_html = (
                '<button type="button" class="btn btn-default btn-sm" '
                'data-toggle="modal" data-target="#modalCharacterAssetContainer" '
                f"data-ajax_children_url={ajax_children_url}>"
                '<i class="fas fa-search"></i></button>'
            )
        else:
            actions_html = ""

        location_name = (
            f"{asset.location.name_plus} ({location_counts.get(asset.location_id, 0)})"
        )
        name_html = create_icon_plus_name_html(
            asset.eve_type.icon_url(DEFAULT_ICON_SIZE), asset.name_display
        )

        data.append(
            {
                "item_id": asset.item_id,
                "location": location_name,
                "name": {
                    "display": name_html,
                    "sort": asset.name_display,
                },
                "quantity": asset.quantity if not asset.is_singleton else "",
                "group": asset.group_display,
                "volume": asset.eve_type.volume,
                "price": asset.price,
                "total": asset.total,
                "actions": actions_html,
                "region": region,
                "solar_system": solar_system,
                "is_ship": is_ship,
            }
        )

    return JsonResponse(data, safe=False)


@login_required
@permission_required("memberaudit.basic_access")
@fetch_character_if_allowed()
def character_asset_container(
    request, character_pk: int, character: Character, parent_asset_pk: int
) -> JsonResponse:
    try:
        parent_asset = character.assets.select_related("location").get(
            pk=parent_asset_pk
        )
    except CharacterAsset.DoesNotExist:
        error_msg = (
            f"Asset with pk {parent_asset_pk} not found for character {character}"
        )
        logger.warning(error_msg)
        context = {
            "error": error_msg,
        }
    else:
        context = {
            "character": character,

memberaudit/templates/memberaudit/partials/character_viewer/overview.html
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

<!-- Character summary panel -->
<div class="panel panel-default">
    <div class="panel-heading">{% translate 'Overview' %}</div>
    <div class="panel-body">
        <div class="character-summary-flex">
            <div class="character-summary-image hidden-xs">
                <p class="text-center">
                    <img width="128" height="128" class="img-rounded"
                        src="{{ auth_character|character_portrait_url:128 }}" />
                </p>

                <p class="text-center">
                    <a href="{{ auth_character|zkillboard_character_url }}" target="_blank">
                        <img src="{% static 'memberaudit/images/zkillboard.png' %}"
                            title="{{ auth_character.character_name }} on zKillboard">
                    </a>

                    <a href="{{ auth_character|evewho_character_url }}" target="_blank">
                        <img src="{{ 1|character_portrait_url:32 }}"
                            title="{{ auth_character.character_name }} on EveWho" width="16px" height="16px">
                    </a>

                    <a href="https://forums.eveonline.com/u/{{ auth_character.character_name.split|join:'_' }}/summary"
                        target="_blank">
                        <img src="{% static 'memberaudit/images/evelogo.png' %}"
                            title="{{ auth_character.character_name }} on Eve Forums" width="16px" height="16px">
                    </a>

                    <a href="https://eve-search.com/search/author/{{ auth_character.character_name }}" target="_blank">
                        <img src="{% static 'memberaudit/images/evesearch.png' %}"
                            title="{{ auth_character.character_name }} on Eve Search" width="16px" height="16px">
                    </a>

                    <a href="https://eve-prism.com/?view=character&name={{ auth_character.character_name }}"
                        target="_blank">
                        <img src="{% static 'memberaudit/images/eve-prism.png' %}"
                            title="{{ auth_character.character_name }} on Eve Prism" width="16px" height="16px">
                    </a>
                </p>
            </div>

            {% translate "(no data yet)" as no_data %}

            <div class="character-summary-info">
                <div class="row">
                    <div class="col-md-6 col-lg-4">
                        <dl class="dl-horizontal">
                            <dt>{% translate 'Character:' %}</dt>
                            <dd class="nowrap">
                                {{ auth_character.character_name }}
                                {% if auth_character.character_id == main_character_id %}
                                &nbsp;<i class="fas fa-crown" title="Main character"></i>
                                {% endif %}

                                {% if character.is_shared %}
                                &nbsp;<i class="far fa-eye" title="Currently shared with recruiters"></i>
                                {% endif %}
                            </dd>

                            <dt>{% translate 'Corporation:' %}</dt>
                            <dd>
                                <a href="{{ auth_character.corporation_name|dotlan_corporation_url }}" target="_blank">
                                    {{ auth_character.corporation_name }}
                                </a>
                            </dd>

                            <dt>{% translate 'Alliance:' %}</dt>
                            <dd>
                                {% if auth_character.alliance_name %}
                                <a href="{{ auth_character.alliance_name|dotlan_alliance_url }}" target="_blank">
                                    {{ auth_character.alliance_name }}
                                </a>
                                {% else %}
                                -
                                {% endif %}
                            </dd>

                            <dt>{% translate 'Faction:' %}</dt>
                            {% if character_details %}
                            <dd>{{ character_details.faction|default:"-" }}</dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Race:' %}</dt>
                            {% if character_details %}
                            <dd>{{ character_details.eve_bloodline.eve_race }} / {{ character_details.eve_bloodline }}
                            </dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}
                        </dl>
                    </div>

                    <div class="col-md-6 col-lg-4">
                        <dl class="dl-horizontal">
                            <dt>{% translate 'Born:' %}</dt>
                            {% if character_details %}
                            <dd>{{ character_details.birthday|naturaltime }}</dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Skillpoints:' %}</dt>
                            {% if character.skillpoints %}
                            <dd>{{ character.skillpoints.total|intword }}</dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Sec. Status:' %}</dt>
                            {% if character_details.security_status %}
                            <dd
                                class="{% if character_details.security_status < 0 %}text-danger{% elif character_details.security_status > 0 %}text-success{% endif %}">
                                {{ character_details.security_status|floatformat:1 }}
                            </dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Assets:' %}</dt>
                            {% if character_assets_total %}
                            <dd>{{ character_assets_total|intword }} ISK (est.)</dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Wallet:' %}</dt>
                            {% if character.wallet_balance %}
                            <dd>{{ character.wallet_balance.total|intword }} ISK</dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}
                        </dl>
                    </div>

                    <div class="col-md-6 col-lg-4">
                        <dl class="dl-horizontal">
                            <dt>{% translate 'Location:' %}</dt>
                            {% if character.location %}
                            <dd>{{ character.location.location.name_plus }}</dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'System:' %}</dt>
                            <dd>{% include 'memberaudit/partials/solar_system.html' with character=character only %}
                            </dd>

                            <dt>{% translate 'Last Login:' %}</dt>
                            {% if character.online_status.last_login %}
                            <dd class="nowrap">{{ character.online_status.last_login|naturaltime }}</dd>
                            {% else %}
                            <dd class="text-muted">{{no_data}}</dd>
                            {% endif %}

                            <dt>{% translate 'Main:' %}</dt>
                            <dd>{{ main|default:"-" }}</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

memberaudit/templates/memberaudit/partials/character_viewer/sidebar.html
{% load i18n %}
{% load static %}
{% load evelinks %}

<!-- Sidebar panel-->
<div class="panel panel-default">
    <div class="panel-heading">Characters</div>
    <div class="panel-body">
        <ul class="sidebar_characters">
            {% for character in all_characters %}
                {% if character.memberaudit_character_pk and character.has_access%}
                    <li class="sidebar_character character-{{ character.memberaudit_character_pk }}{% if auth_character.character_name == character.character_name %} active{% endif %}">
                        <a href="{% url 'memberaudit:character_viewer' character.memberaudit_character_pk %}">
                            {% include "memberaudit/partials/character_viewer/sidebar_character.html" %}
                        </a>
                    </li>
                {% else %}
                    <li class="sidebar_character_disabled">
                        {% include "memberaudit/partials/character_viewer/sidebar_character.html" %}
                    </li>
                {% endif %}

            {% endfor %}
        </ul>
    </div>
</div>

memberaudit/templates/memberaudit/partials/character_viewer/sidebar_character.html
{% load i18n %}
{% load evelinks %}

<img height="20" width="20" src="{{ character.character_id|character_portrait_url:32 }}"/>
<span
    {% if not character.memberaudit_character_pk %}class="text-muted"{% endif%}>{{ character.character_name }}

    {% if character.character_id == main_character_id %}
        &nbsp;<i class="fas fa-crown" title="{% translate 'Main character' %}"></i>
    {% endif %}

    {% if character.is_shared %}
        &nbsp;<i class="far fa-eye" title="{% translate 'Currently shared with recruiters' %}"></i>
    {% endif %}
</span>

memberaudit/templates/memberaudit/partials/character_viewer/tabs_navigation.html
{% load i18n %}

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation">
        <a href="#assets" aria-controls="assets" role="tab" data-toggle="tab">
            {% translate 'Assets' %}
            {% if is_assets_updating %}&nbsp;<i class="fas fa-exclamation-circle" title="{% translate 'Update in progress...' %}"></i>{% endif %}
        </a>
    </li>
    <li role="presentation"><a href="#attributes" aria-controls="attributes" role="tab" data-toggle="tab">{% translate 'Attributes' %}</a></li>
    <li role="presentation"><a href="#bio" aria-controls="bio" role="tab" data-toggle="tab">{% translate 'Bio' %}</a></li>
    <li role="presentation"><a href="#contacts" aria-controls="contacts" role="tab" data-toggle="tab">{% translate 'Contacts' %}</a></li>
    <li role="presentation"><a href="#contracts" aria-controls="contracts" role="tab" data-toggle="tab">{% translate 'Contracts' %}</a></li>
    <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">{% translate 'Corporations' %}</a></li>
    <li role="presentation"><a href="#implants" aria-controls="implants" role="tab" data-toggle="tab">{% translate 'Implants' %}</a></li>
    <li role="presentation"><a href="#clones" aria-controls="clones" role="tab" data-toggle="tab">{% translate 'Jump Clones' %}</a></li>
    <li role="presentation"><a href="#loyalty" aria-controls="loyalty" role="tab" data-toggle="tab">{% translate 'Loyalty' %}</a></li>
    <li role="presentation"><a href="#mail" aria-controls="mail" role="tab" data-toggle="tab">{% translate 'Mails' %}</a></li>
    {% if perms.memberaudit.view_roles %}
    <li role="presentation"><a href="#roles" aria-controls="skillqueue" role="tab" data-toggle="tab">{% translate 'Roles' %}</a></li>
    {% endif %}
    <li role="presentation"><a href="#skillqueue" aria-controls="skillqueue" role="tab" data-toggle="tab">{% translate 'Skill Queue' %}</a></li>
    <li role="presentation"><a href="#skill_sets" aria-controls="skill_sets" role="tab" data-toggle="tab">{% translate 'Skill Sets' %}</a></li>
    <li role="presentation"><a href="#skills" aria-controls="skills" role="tab" data-toggle="tab">{% translate 'Skills' %}</a></li>
    <li class="dropdown active" role="presentation" role="tab" aria-controls="wallet">
        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">{% translate 'Wallet' %}&nbsp;<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1">
        <li class=""><a href="#wallet_journal" tabindex="-1" data-toggle="tab">{% translate 'Transactions' %}</a></li>
        <li class=""><a href="#wallet_transactions" tabindex="-1" data-toggle="tab">{% translate 'Market Transactions' %}</a></li>
        </ul>
    </li>
</ul>