memberaudit/urls.py
from django.urls import path

from . import views

app_name = "memberaudit"

urlpatterns = [
    path("", views.index, name="index"),
    path("launcher", views.launcher, name="launcher"),
    path(
        "character_viewer/<int:character_pk>/",
        views.character_viewer,
        name="character_viewer",
    ),
    path("add_character", views.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        views.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        views.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        views.unshare_character,
        name="unshare_character",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        views.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        views.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        views.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        views.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        views.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        views.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        views.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        views.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        views.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail_data/<int:character_pk>/<int:mail_pk>/",
        views.character_mail_data,
        name="character_mail_data",
    ),
    path(
        "character_roles_data/<int:character_pk>/",
        views.character_roles_data,
        name="character_roles_data",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        views.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        views.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        views.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        views.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        views.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path("character_finder", views.character_finder, name="character_finder"),
    path(
        "character_finder_data",
        views.character_finder_data,
        name="character_finder_data",
    ),
    path("reports", views.reports, name="reports"),
    path(
        "user_compliance_report_data",
        views.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        views.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        views.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        views.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        views.character_attribute_data,
        name="character_attribute_data",
    ),
]

memberaudit/models/sections.py
"""
Character sections models
"""

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from eveuniverse.models import (
    EveAncestry,
    EveBloodline,
    EveEntity,
    EveFaction,
    EveRace,
    EveSolarSystem,
    EveType,
)

from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag

from .. import __title__
from ..core.xml_converter import eve_xml_to_html
from ..managers.sections import (
    CharacterAssetManager,
    CharacterAttributesManager,
    CharacterContactLabelManager,
    CharacterContactManager,
    CharacterContractBidManager,
    CharacterContractItemManager,
    CharacterContractManager,
    CharacterCorporationHistoryManager,
    CharacterDetailsManager,
    CharacterImplantManager,
    CharacterJumpCloneManager,
    CharacterLocationManager,
    CharacterLoyaltyEntryManager,
    CharacterMailLabelManager,
    CharacterMailManager,
    CharacterRoleManager,
    CharacterSkillManager,
    CharacterSkillqueueEntryManager,
    CharacterSkillSetCheckManager,
    CharacterWalletJournalEntryManager,
    CharacterWalletTransactionManager,
)
from .character import Character
from .constants import CURRENCY_MAX_DECIMALS, CURRENCY_MAX_DIGITS, NAMES_MAX_LENGTH
from .general import Location

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


class CharacterAsset(models.Model):
    """An Eve Online asset belonging to a Character"""

    character = models.ForeignKey(
        Character, on_delete=models.CASCADE, related_name="assets"
    )
    item_id = models.PositiveBigIntegerField()

    location = models.ForeignKey(
        Location, on_delete=models.CASCADE, default=None, null=True
    )
    parent = models.ForeignKey(
        "CharacterAsset",
        on_delete=models.CASCADE,
        default=None,
        null=True,
        related_name="children",
    )

    eve_type = models.ForeignKey(EveType, on_delete=models.CASCADE, related_name="+")
    is_blueprint_copy = models.BooleanField(default=None, null=True, db_index=True)
    is_singleton = models.BooleanField()
    location_flag = models.CharField(max_length=NAMES_MAX_LENGTH)
    name = models.CharField(max_length=NAMES_MAX_LENGTH, default="")
    quantity = models.PositiveIntegerField()

    objects = CharacterAssetManager()

    class Meta:
        default_permissions = ()
        constraints = [
            models.UniqueConstraint(
                fields=["character", "item_id"],
                name="functional_pk_characterasset",
            )
        ]

    def __str__(self) -> str:
        return f"{self.character}-{self.item_id}-{self.name_display}"

    @property
    def name_display(self) -> str:
        """name of this asset to be displayed to user"""
        name = self.name if self.name else self.eve_type.name
        if self.is_blueprint_copy:
            name += " [BPC]"
        return name

    @property
    def icon_url(self) -> str:
        variant = self.eve_type.IconVariant.BPC if self.is_blueprint_copy else None
        return self.eve_type.icon_url(variant=variant)

    @property
    def group_display(self) -> str:
        """group of this asset to be displayed to user"""
        return self.eve_type.name if self.name else self.eve_type.eve_group.name


class CharacterContactLabel(models.Model):
    """An Eve Online contact label belonging to a Character"""

    character = models.ForeignKey(
        Character, on_delete=models.CASCADE, related_name="contact_labels"
    )
    label_id = models.PositiveBigIntegerField()
    name = models.CharField(max_length=NAMES_MAX_LENGTH)

    objects = CharacterContactLabelManager()

    class Meta:
        default_permissions = ()
        constraints = [
            models.UniqueConstraint(
                fields=["character", "label_id"],
                name="functional_pk_characterlabel",
            )
        ]

    def __str__(self) -> str:
        return f"{self.character}-{self.name}"


class CharacterContact(models.Model):
    """An Eve Online contact belonging to a Character"""

    STANDING_EXCELLENT = _("excellent standing")
    STANDING_GOOD = _("good standing")
    STANDING_NEUTRAL = _("neutral standing")
    STANDING_BAD = _("bad standing")
    STANDING_TERRIBLE = _("terrible standing")

    character = models.ForeignKey(
        Character, on_delete=models.CASCADE, related_name="contacts"
    )
    eve_entity = models.ForeignKey(
        EveEntity, on_delete=models.CASCADE, related_name="+"
    )

    is_blocked = models.BooleanField(default=None, null=True)
    is_watched = models.BooleanField(default=None, null=True)
    standing = models.FloatField()
    labels = models.ManyToManyField(CharacterContactLabel, related_name="contacts")

    objects = CharacterContactManager()

    class Meta:
        default_permissions = ()
        constraints = [
            models.UniqueConstraint(
                fields=["character", "eve_entity"],
                name="functional_pk_charactercontact",
            )
        ]

    def __str__(self) -> str:
        return f"{self.character}-{self.eve_entity.name}"

    @property
    def standing_level(self) -> int:
        if self.standing > 5:
            return self.STANDING_EXCELLENT

        if 5 >= self.standing > 0:
            return self.STANDING_GOOD

        if self.standing == 0:
            return self.STANDING_NEUTRAL

        if 0 > self.standing >= -5:
            return self.STANDING_BAD

        if self.standing < -5:
            return self.STANDING_TERRIBLE


class CharacterContract(models.Model):
    """An Eve Online contract belonging to a Character"""

    AVAILABILITY_ALLIANCE = "AL"
    AVAILABILITY_CORPORATION = "CO"
    AVAILABILITY_PERSONAL = "PR"
    AVAILABILITY_PUBLIC = "PU"
    AVAILABILITY_CHOICES = (
        (AVAILABILITY_ALLIANCE, _("alliance")),
        (AVAILABILITY_CORPORATION, _("corporation")),
        (AVAILABILITY_PERSONAL, _("private")),
        (AVAILABILITY_PUBLIC, _("public")),
    )
    ESI_AVAILABILITY_MAP = {
        "alliance": AVAILABILITY_ALLIANCE,
        "corporation": AVAILABILITY_CORPORATION,
        "personal": AVAILABILITY_PERSONAL,
        "public": AVAILABILITY_PUBLIC,
    }

    STATUS_OUTSTANDING = "OS"
    STATUS_IN_PROGRESS = "IP"
    STATUS_FINISHED_ISSUER = "FI"
    STATUS_FINISHED_CONTRACTOR = "FC"
    STATUS_FINISHED = "FS"
    STATUS_CANCELED = "CA"
    STATUS_REJECTED = "RJ"
    STATUS_FAILED = "FL"
    STATUS_DELETED = "DL"
    STATUS_REVERSED = "RV"
    STATUS_CHOICES = (
        (STATUS_CANCELED, _("canceled")),
        (STATUS_DELETED, _("deleted")),
        (STATUS_FAILED, _("failed")),
        (STATUS_FINISHED, _("finished")),
        (STATUS_FINISHED_CONTRACTOR, _("finished contractor")),
        (STATUS_FINISHED_ISSUER, _("finished issuer")),
        (STATUS_IN_PROGRESS, _("in progress")),
        (STATUS_OUTSTANDING, _("outstanding")),
        (STATUS_REJECTED, _("rejected")),
        (STATUS_REVERSED, _("reversed")),
    )
    ESI_STATUS_MAP = {
        "canceled": STATUS_CANCELED,
        "deleted": STATUS_DELETED,
        "failed": STATUS_FAILED,
        "finished": STATUS_FINISHED,
        "finished_contractor": STATUS_FINISHED_CONTRACTOR,
        "finished_issuer": STATUS_FINISHED_ISSUER,
        "in_progress": STATUS_IN_PROGRESS,
        "outstanding": STATUS_OUTSTANDING,
        "rejected": STATUS_REJECTED,
        "reversed": STATUS_REVERSED,
    }

    TYPE_AUCTION = "AT"
    TYPE_COURIER = "CR"
    TYPE_ITEM_EXCHANGE = "IE"
    TYPE_LOAN = "LN"
    TYPE_UNKNOWN = "UK"
    TYPE_CHOICES = (
        (TYPE_AUCTION, _("auction")),
        (TYPE_COURIER, _("courier")),
        (TYPE_ITEM_EXCHANGE, _("item exchange")),
        (TYPE_LOAN, _("loan")),
        (TYPE_UNKNOWN, _("unknown")),
    )
    ESI_TYPE_MAP = {
        "auction": TYPE_AUCTION,
        "courier": TYPE_COURIER,
        "item_exchange": TYPE_ITEM_EXCHANGE,
        "loan": TYPE_LOAN,
        "unknown": TYPE_UNKNOWN,
    }

    character = models.ForeignKey(
        Character,
        on_delete=models.CASCADE,
        related_name="contracts",
    )
    contract_id = models.IntegerField()

    acceptor = models.ForeignKey(
        EveEntity,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        related_name="+",
        help_text="Who will accept the contract if character",
    )
    acceptor_corporation = models.ForeignKey(
        EveEntity,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        related_name="+",
        help_text="corporation of acceptor",
    )
    assignee = models.ForeignKey(
        EveEntity,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        related_name="+",
        help_text="To whom the contract is assigned, can be a corporation or a character",
    )
    availability = models.CharField(
        max_length=2,
        choices=AVAILABILITY_CHOICES,
        help_text="To whom the contract is available",
    )
    buyout = models.DecimalField(
        max_digits=CURRENCY_MAX_DIGITS,
        decimal_places=CURRENCY_MAX_DECIMALS,
        default=None,
        null=True,
    )
    collateral = models.DecimalField(
        max_digits=CURRENCY_MAX_DIGITS,
        decimal_places=CURRENCY_MAX_DECIMALS,
        default=None,
        null=True,
    )
    contract_type = models.CharField(max_length=2, choices=TYPE_CHOICES)
    date_accepted = models.DateTimeField(default=None, null=True)
    date_completed = models.DateTimeField(default=None, null=True)
    date_expired = models.DateTimeField()
    date_issued = models.DateTimeField()
    days_to_complete = models.IntegerField(default=None, null=True)
    end_location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        related_name="contract_end_location",
        default=None,
        null=True,
    )

memberaudit/templates/memberaudit/modals/character_viewer/character_skill_set_details.html
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

<div class="modal" id="modalCharacterSkillSetDetails" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document" id="modalCharacterSkillSetContents">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
                        &times;
                    </span>
                </button>
                <h4 class="modal-title" id="myModalLabel">{% translate 'Loading...' %}</h4>
            </div>

            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-striped table-width-fix" id="skill_set_details">
                        <thead>
                            <tr>
                                <th>{% translate 'Name' %}</th>
                                <th class="text-center">{% translate 'Required' %}</th>
                                <th class="text-center">{% translate 'Recommended' %}</th>
                                <th class="text-center">{% translate 'Current' %}</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody></tbody>
                    </table>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    {% translate 'Close' %}
                </button>
            </div>
        </div>
    </div>
</div>

memberaudit/templates/memberaudit/modals/character_viewer/contract.html
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

<!-- Modal for Contracts -->
<div class="modal" id="modalCharacterContract" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-xl" role="document" id="modalCharacterContractContent">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
                    &times;
                </span></button>
                <h4 class="modal-title" id="myModalLabel">{% translate 'Loading...' %}</h4>
            </div>

            <div class="modal-body">
                {% if NIGHT_MODE %}
                    <img src="{% static 'memberaudit/images/Spinner-1s-64px-dark.gif' %}"/>
                {% else %}
                    <img src="{% static 'memberaudit/images/Spinner-1s-64px-light.gif' %}"/>
                {% endif %}
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    {% translate 'Close' %}
                </button>
            </div>
        </div>
    </div>
</div>

memberaudit/templates/memberaudit/modals/character_viewer/contract_content.html
{% load humanize %}
{% load i18n %}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
            &times;
        </span></button>
        <h4 class="modal-title" id="myModalLabel">{{ contract_summary }}</h4>
    </div>
    <div class="modal-body">
        {% if error %}
            <p class="text-danger">{{ error }}</p>
        {% else %}
            <dl class="dl-horizontal">
                <dt>{% translate 'Info by Issuer:' %}</dt> <dd>{{ contract.title|default:"(None)" }}</dd>
                <dt>{% translate 'Type:' %}</dt> <dd>{{ contract.get_contract_type_display|title }}</dd>
                <dt>{% translate 'Issued By:' %}</dt> <dd>{{ contract.issuer.name }}</dd>
                <dt>{% translate 'Availability:' %}</dt>
                <dd>
                    {{ contract.get_availability_display|title }}
                    {% if contract.availability == contract.AVAILABILITY_PUBLIC  %}
                        - {% translate 'Region:' %} {{ contract.start_location.eve_solar_system.eve_constellation.eve_region }}
                    {% else %}
                        - {{ contract.assignee.name }}
                    {% endif %}
                </dd>
                <dt>{% translate 'Status:' %}</dt> <dd>{{ contract.get_status_display|title }}</dd>
                <dt>{% translate 'Location:' %}</dt>
                <dd>
                    <a href="{{ contract.start_location.solar_system_url }}" target="_blank">
                        {{ contract.start_location.name }}
                    </a>
                </dd>
                <dt>{% translate 'Date Issued:' %}</dt> <dd>{{ contract.date_issued|date:MY_DATETIME_FORMAT }}</dd>
                <dt>{% translate 'Expiration Date:' %}</dt> <dd>{{ contract.date_expired|date:MY_DATETIME_FORMAT }}</dd>
                <hr>
                {% if contract.contract_type == contract.TYPE_COURIER %}
                    <dt>{% translate 'Complete In:' %}</dt> <dd>{{ contract.days_to_complete }}</dd>
                    <dt>{% translate 'Volume:' %}</dt> <dd>{{ contract.volume|floatformat:2|intcomma }} {% translate 'm3' %}</dd>
                    <dt>{% translate 'Reward:' %}</dt> <dd>{{ contract.reward|floatformat:2|intcomma }} {% translate 'ISK' %}</dd>
                    <dt>{% translate 'Collateral:' %}</dt> <dd>{{ contract.collateral|floatformat:2|intcomma }}</dd>
                    <dt>{% translate 'Destination:' %}</dt>
                    <dd>
                        <a href="{{ contract.end_location.solar_system_url }}" target="_blank">
                            {{ contract.end_location.name }}
                        </a>
                    </dd>
                {% elif contract.contract_type == contract.TYPE_ITEM_EXCHANGE %}
                    {% if contract.price or has_items_requested %}
                        <h4 class="text-danger">{% translate 'Buyer will pay' %}</h4>
                        {% if contract.price %}
                            <p>{{ contract.price|floatformat:2|intcomma }} {% translate 'ISK' %}</p>
                        {% endif %}
                        {% if has_items_requested %}
                            {% include "memberaudit/modals/character_viewer/contract_items.html" with table_name="tab_contract_items_requested" %}
                        {% endif %}
                    {% endif %}

                    <hr>

                    {% if contract.reward or has_items_included %}
                        <h4 class="text-success">{% translate 'Buyer will get' %}</h4>
                        {% if contract.reward %}
                            <p>{{ contract.reward|floatformat:2|intcomma }} {% translate 'ISK' %}</p>
                        {% endif %}
                        {% if has_items_included %}
                            {% include "memberaudit/modals/character_viewer/contract_items.html" with table_name="tab_contract_items_included" %}
                        {% endif %}
                    {% endif %}
                {% elif contract.contract_type == contract.TYPE_AUCTION %}
                    <dt>Starting Bid:</dt> <dd>{{ contract.price|floatformat:2|intcomma }}</dd>
                    <dt>Buyout Price:</dt> <dd>{{ contract.buyout|floatformat:2|intcomma }}</dd>
                    <dt>Current Bid:</dt> <dd>{{ current_bid|floatformat:2|intcomma }} ({{ bids_count }} {% translate 'so far' %})</dd>
                    <dt>Time Left:</dt> <dd>{{ contract.date_expired|timeuntil }}</dd>

                    <hr>

                    <h4 class="text-success">{% translate 'Buyer will get' %}</h4>
                    {% if has_items_included %}
                        {% include "memberaudit/modals/character_viewer/contract_items.html" with table_name="tab_contract_items_included" %}
                    {% endif %}
                {% endif %}
            </dl>
        {% endif %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            {% translate 'Close' %}
        </button>
    </div>
</div>

<script>
    $(document).ready(function () {
        {% if has_items_requested or has_items_included %}
            var columns = [
                { data: 'name',
                    render: {
                        _: 'display',
                        sort: 'sort'
                    }
                },
                {
                    data: 'quantity',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
                { data: 'group' },
                { data: 'category' },
                {
                    data: 'price',
                    render: $.fn.dataTable.render.number( ',', '.', 2 )
                },
                {
                    data: 'total',
                    render: $.fn.dataTable.render.number( ',', '.', 2 )
                }
            ]
            var order = [[0, "asc"]]
            var footerCallback = function ( row, data, start, end, display ) {
                var api = this.api(), data;

                // Remove the formatting to get integer data for summation
                var intVal = function ( i ) {
                    return typeof i === 'string' ?
                        i.replace(/[\$,]/g, '')*1 :
                        typeof i === 'number' ?
                            i : 0;
                };

                // Total over all pages
                var total = api
                    .column( 5 )
                    .data()
                    .reduce( function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0 );

                // Update footer
                $( api.column( 5 ).footer() ).html(
                    total.toLocaleString(
                        {minimumFractionDigits: 2, maximumFractionDigits: 2}
                    )
                );
            }
        {% endif %}
        {% if has_items_requested %}
            $('#tab_contract_items_requested').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:character_contract_items_requested_data' character.pk contract.pk %}",
                    dataSrc: '',
                    cache: false
                },
                columns: columns,
                order: order,
                footerCallback: footerCallback
            });
        {% endif %}

        {% if has_items_included %}
            $('#tab_contract_items_included').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:character_contract_items_included_data' character.pk contract.pk %}",
                    dataSrc: '',
                    cache: false
                },
                columns: columns,
                order: order,
                footerCallback: footerCallback
            });
        {% endif %}
    });
</script>

memberaudit/templates/memberaudit/modals/character_viewer/contract_items.html
{% load i18n %}

<table class="table table-striped table-width-fix" id="{{ table_name }}">
    <thead>
        <tr>
            <th>{% translate 'Name' %}</th>
            <th>{% translate 'Qty' %}</th>
            <th>{% translate 'Type' %}</th>
            <th>{% translate 'Category' %}</th>
            <th>{% translate 'Price' %}</th>
            <th>{% translate 'Total' %}</th>
        </tr>
    </thead>

    <tbody></tbody>

    <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th>Grand Total:</th>
            <th></th>
        </tr>
    </tfoot>

</table>

memberaudit/templates/memberaudit/modals/character_viewer/mail.html
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

<!-- Modal for Mails -->
<div class="modal" id="modalCharacterMail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">
                    &times;
                </span></button>
                <h4 class="modal-title" id="myModalLabel">{% translate 'Loading...' %}</h4>
            </div>

            <div class="modal-body">

                <div id="div_mail_body_loader">
                    {% if NIGHT_MODE %}
                        <img src="{% static 'memberaudit/images/Spinner-1s-64px-dark.gif' %}"/>
                    {% else %}
                        <img src="{% static 'memberaudit/images/Spinner-1s-64px-light.gif' %}"/>
                    {% endif %}
                </div>

                <div id="div_mail_body_main" style="display: none !important;">
                    <dl class="dl-horizontal">
                        <dt>{% translate 'From:' %}</dt>
                        <dd id="mail_from">{% translate 'Loading...' %}</dd>
                        <dt>{% translate 'To:' %}</dt>
                        <dd id="mail_to">{% translate 'Loading...' %}</dd>
                        <dt>{% translate 'Sent:' %}</dt>
                        <dd id="mail_sent">{% translate 'Loading...' %}</dd>
                        <br>
                        <div id="mail_body">{% translate 'Loading...' %}</div>
                    </dl>
                </div>

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    {% translate 'Close' %}
                </button>
            </div>
        </div>
    </div>
</div>