memberaudit/urls.py
from django.urls import path

from . import views

app_name = "memberaudit"

urlpatterns = [
    path("", views.index, name="index"),
    path("launcher", views.launcher, name="launcher"),
    path(
        "character_viewer/<int:character_pk>/",
        views.character_viewer,
        name="character_viewer",
    ),
    path("add_character", views.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        views.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        views.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        views.unshare_character,
        name="unshare_character",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        views.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        views.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        views.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        views.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        views.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        views.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        views.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        views.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        views.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail_data/<int:character_pk>/<int:mail_pk>/",
        views.character_mail_data,
        name="character_mail_data",
    ),
    path(
        "character_roles_data/<int:character_pk>/",
        views.character_roles_data,
        name="character_roles_data",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        views.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        views.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        views.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        views.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        views.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path("character_finder", views.character_finder, name="character_finder"),
    path(
        "character_finder_data",
        views.character_finder_data,
        name="character_finder_data",
    ),
    path("reports", views.reports, name="reports"),
    path(
        "user_compliance_report_data",
        views.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        views.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        views.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        views.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        views.character_attribute_data,
        name="character_attribute_data",
    ),
]

memberaudit/views/character_finder.py
"""
views for character_finder actions
"""

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.html import format_html
from django.utils.safestring import mark_safe

from memberaudit.helpers import eve_solar_system_to_html
from memberaudit.models import Character
from memberaudit.utils import create_fa_button_html, yesno_str
from memberaudit.views.utils import add_common_context, create_icon_plus_name_html


@login_required
@permission_required("memberaudit.finder_access")
def character_finder(request) -> HttpResponse:
    context = {
        "page_title": "Character Finder",
    }
    return render(
        request,
        "memberaudit/character_finder.html",
        add_common_context(request, context),
    )


@login_required
@permission_required("memberaudit.finder_access")
def character_finder_data(request) -> JsonResponse:
    character_list = list()
    for character in (
        Character.objects.user_has_access(user=request.user)
        .select_related(
            "character_ownership__character",
            "character_ownership__user",
            "character_ownership__user__profile__main_character",
            "character_ownership__user__profile__state",
        )
        .prefetch_related(
            "location",
            "location__eve_solar_system",
            "location__eve_solar_system__eve_constellation__eve_region",
        )
    ):
        auth_character = character.character_ownership.character
        character_viewer_url = reverse(
            "memberaudit:character_viewer", args=[character.pk]
        )
        actions_html = create_fa_button_html(
            url=character_viewer_url,
            fa_code="fas fa-search",
            button_type="primary",
        )
        alliance_name = (
            auth_character.alliance_name if auth_character.alliance_name else ""
        )
        character_organization = format_html(
            "{}<br><em>{}</em>", auth_character.corporation_name, alliance_name
        )
        user_profile = character.character_ownership.user.profile
        try:
            main_html = create_icon_plus_name_html(
                user_profile.main_character.portrait_url(),
                user_profile.main_character.character_name,
                avatar=True,
            )

        except AttributeError:
            main_html = ""

        text = format_html(
            "{}&nbsp;{}",
            mark_safe('&nbsp;<i class="fas fa-crown" title="Main character">')
            if character.is_main
            else "",
            mark_safe('&nbsp;<i class="far fa-eye" title="Shared character">')
            if character.is_shared
            else "",
        )
        character_html = create_icon_plus_name_html(
            auth_character.portrait_url(),
            auth_character.character_name,
            avatar=True,
            url=character_viewer_url,
            text=text,
        )

        try:
            location_name = (
                character.location.location.name if character.location.location else ""
            )
            solar_system_html = eve_solar_system_to_html(
                character.location.eve_solar_system
            )
            location_html = format_html("{}<br>{}", location_name, solar_system_html)
            solar_system_name = character.location.eve_solar_system.name
            region_name = (
                character.location.eve_solar_system.eve_constellation.eve_region.name
            )
        except ObjectDoesNotExist:
            location_html = ""
            solar_system_name = ""
            region_name = ""

        character_list.append(
            {
                "character_pk": character.pk,
                "character": {
                    "display": character_html,
                    "sort": auth_character.character_name,
                },
                "character_organization": character_organization,
                "main": main_html,
                "state_name": user_profile.state.name,
                "location": location_html,
                "actions": actions_html,
                "corporation_name": auth_character.corporation_name,
                "alliance_name": alliance_name,
                "solar_system_name": solar_system_name,
                "region_name": region_name,
                "main_str": yesno_str(character.is_main),
            }
        )
    return JsonResponse(character_list, safe=False)

memberaudit/views/reports.py
"""
views for reports actions
"""

from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Count, Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.html import format_html

from eveuniverse.core import eveimageserver

from memberaudit.models import Character, SkillSetGroup, accessible_users
from memberaudit.utils import yesno_str
from memberaudit.views.constants import (
    DEFAULT_ICON_SIZE,
    SKILL_SET_DEFAULT_ICON_TYPE_ID,
    UNGROUPED_SKILL_SET,
)
from memberaudit.views.utils import (
    add_common_context,
    create_icon_plus_name_html,
    create_main_organization_html,
)


@login_required
@permission_required("memberaudit.reports_access")
def reports(request) -> HttpResponse:
    context = {
        "page_title": "Reports",
    }
    return render(
        request,
        "memberaudit/reports.html",
        add_common_context(request, context),
    )


@login_required
@permission_required("memberaudit.reports_access")
def compliance_report_data(request) -> JsonResponse:
    users_and_character_counts = (
        accessible_users(request.user)
        .annotate(total_chars=Count("character_ownerships__character", distinct=True))
        .annotate(
            unregistered_chars=Count(
                "character_ownerships",
                filter=Q(character_ownerships__memberaudit_character=None),
                distinct=True,
            )
        )
        .select_related("profile__main_character")
    )

    user_data = list()
    for user in users_and_character_counts:
        if user.profile.main_character:
            main_character = user.profile.main_character
            main_name = main_character.character_name
            main_html = create_icon_plus_name_html(
                main_character.portrait_url(),
                main_character.character_name,
                avatar=True,
            )
            corporation_name = main_character.corporation_name
            organization_html = create_main_organization_html(main_character)
            alliance_name = (
                main_character.alliance_name if main_character.alliance_name else ""
            )

            is_compliant = user.unregistered_chars == 0
        else:
            main_html = main_name = user.username
            alliance_name = organization_html = corporation_name = ""
            is_compliant = False

        is_registered = user.unregistered_chars < user.total_chars

        user_data.append(
            {
                "id": user.pk,
                "main": {
                    "display": main_html,
                    "sort": main_name,
                },
                "organization": {
                    "display": organization_html,
                    "sort": corporation_name,
                },
                "corporation_name": corporation_name,
                "alliance_name": alliance_name,
                "total_chars": user.total_chars,
                "unregistered_chars": user.unregistered_chars,
                "is_registered": is_registered,
                "registered_str": yesno_str(is_registered),
                "is_compliant": is_compliant,
                "compliance_str": yesno_str(is_compliant),
            }
        )

    return JsonResponse(user_data, safe=False)


@login_required
@permission_required("memberaudit.reports_access")
def skill_sets_report_data(request) -> JsonResponse:
    def create_data_row(group) -> dict:
        user = character.character_ownership.user
        auth_character = character.character_ownership.character
        main_character = user.profile.main_character
        main_html = create_icon_plus_name_html(
            user.profile.main_character.portrait_url(),
            main_character.character_name,
            avatar=True,
        )
        main_corporation = main_character.corporation_name
        main_alliance = (
            main_character.alliance_name if main_character.alliance_name else ""
        )
        organization_html = format_html(
            "{}{}",
            main_corporation,
            f" [{main_character.alliance_ticker}]"
            if main_character.alliance_name
            else "",
        )
        character_viewer_url = "{}?tab=skill_sets".format(
            reverse("memberaudit:character_viewer", args=[character.pk])
        )
        character_html = create_icon_plus_name_html(
            auth_character.portrait_url(),
            auth_character.character_name,
            avatar=True,
            url=character_viewer_url,
        )
        group_pk = group.pk if group else 0
        has_required = [
            create_icon_plus_name_html(
                obj.skill_set.ship_type.icon_url(DEFAULT_ICON_SIZE)
                if obj.skill_set.ship_type
                else eveimageserver.type_icon_url(
                    SKILL_SET_DEFAULT_ICON_TYPE_ID, size=DEFAULT_ICON_SIZE
                ),
                obj.skill_set.name,
            )
            for obj in skill_set_qs
        ]
        has_required_html = (
            "<br>".join(has_required)
            if has_required
            else '<i class="fas fa-times boolean-icon-false"></i>'
        )
        return {
            "id": f"{group_pk}_{character.pk}",
            "group": group.name_plus if group else UNGROUPED_SKILL_SET,
            "main": main_character.character_name,
            "main_html": main_html,
            "organization_html": organization_html,
            "corporation": main_corporation,
            "alliance": main_alliance,
            "character": character.character_ownership.character.character_name,
            "character_html": character_html,
            "has_required": has_required_html,
            "has_required_str": yesno_str(bool(has_required)),
            "is_doctrine_str": yesno_str(group.is_doctrine if group else False),
        }

    data = list()

    character_qs = (
        Character.objects.select_related("character_ownership__user")
        .select_related(
            "character_ownership__user",
            "character_ownership__user__profile__main_character",
            "character_ownership__character",
        )
        .prefetch_related("skill_set_checks")
        .filter(character_ownership__user__in=list(accessible_users(request.user)))
    )

    my_select_related = "skill_set", "skill_set__ship_type"
    for group in SkillSetGroup.objects.all():
        for character in character_qs:
            skill_set_qs = (
                character.skill_set_checks.select_related(*my_select_related)
                .filter(skill_set__groups=group, failed_required_skills__isnull=True)
                .order_by("skill_set__name")
            )
            data.append(create_data_row(group))

    for character in character_qs:
        if (
            character.skill_set_checks.select_related(*my_select_related)
            .filter(skill_set__groups__isnull=True)
            .exists()
        ):
            skill_set_qs = character.skill_set_checks.filter(
                skill_set__groups__isnull=True, failed_required_skills__isnull=True
            ).order_by("skill_set__name")
            data.append(create_data_row(None))

    return JsonResponse(data, safe=False)

memberaudit/templates/memberaudit/analysis/character_finder.html
{% extends 'memberaudit/analysis/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}


{% block details %}
    
    <div class="panel panel-default">   
        <div class="panel-heading">
            <h3 class="panel-title">Characters</h3>
        </div>
        <div class="panel-body">        
            <div class="table-responsive">
                <table class="table table-striped" id="tab_characters">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Character</th>                        
                            <th>Corporation</th>
                            <th>Alliance</th>
                            <th>Main</th>
                            <th>State</th>
                            <th></th>                            
                        </tr>
                    </thead>
                    <tbody>                   
                    </tbody>                
                </table>
            </div>
        </div>
    </div>        
    
{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}    
    
    <!--load JS for filterDropDown plugin -->
    <script type="text/javascript" src="{% static 'js/filterDropDown/filterDropDown.min.js' %}">
    </script>
    
    <script>
        $(document).ready(function() {
            $('#tab_characters').DataTable({            
                ajax: {
                    url: '{% url 'memberaudit:character_finder_data' %}',
                    dataSrc: '',
                    cache: false
                },

                columns: [
                    { data: 'portrait' },
                    { data: 'character' },
                    { data: 'corporation' },                
                    { data: 'alliance' },
                    { data: 'main' },
                    { data: 'state' },
                    { data: 'actions' },
                ],

                columnDefs: [														
                    { "orderable": false, "targets": [ 0 ] },                
                ],

                order: [ [ 1, "asc" ] ],

                filterDropDown: {										
                    columns: [
                        {
                            idx: 2
                        },
                        {
                            idx: 3
                        },
                        {
                            idx: 4
                        },
                        {
                            idx: 5
                        },
                    ],
                    bootstrap: true
                }
            });       
        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link href="{% static 'memberaudit/contracts.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
    
{% endblock %}

memberaudit/templates/memberaudit/analysis/reports.html
{% extends 'memberaudit/analysis/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}


{% block details %}
    
    <div class="panel panel-default">   
        <div class="panel-body">        
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#compliance" aria-controls="compliance" role="tab" data-toggle="tab">
                            User Compliance
                        </a>
                    </li>
                    <li role="presentation" class="disabled">
                        <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">
                            Dummy 1
                        </a>
                    </li>
                    <li role="presentation" class="disabled">
                        <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
                            Dummy 2
                        </a>
                    </li>
                    <li role="presentation" class="disabled">
                        <a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">
                            Dummy 3
                        </a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="compliance">
                        <h3>User Compliance</h3>
                        <div class="table-responsive">
                            <table class="table table-striped" id="tab_contracts">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>User</th>
                                        <th>Main</th>                        
                                        <th>Corporation</th>
                                        <th>Alliance</th>
                                        <th>Total Chars</th>
                                        <th>Unregistered Chars</th>
                                        <th>Compliant?</th>                            
                                    </tr>
                                </thead>
                                <tbody>                   
                                </tbody>                
                            </table>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">...</div>
                    <div role="tabpanel" class="tab-pane" id="messages">...</div>
                    <div role="tabpanel" class="tab-pane" id="settings">...</div>
                </div>
            </div>
            
        </div>
    </div>        
    
{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}    
    
    <!--load JS for filterDropDown plugin -->
    <script type="text/javascript" src="{% static 'js/filterDropDown/filterDropDown.min.js' %}">
    </script>
    
    <script>
        $(document).ready(function() {
            $('#tab_contracts').DataTable({            
                ajax: {
                    url: '{% url 'memberaudit:compliance_report_data' %}',
                    dataSrc: '',
                    cache: false
                },

                columns: [
                    { data: 'portrait' },
                    { data: 'name' },
                    { data: 'main' },                
                    { data: 'corporation' },
                    { data: 'alliance' },
                    { data: 'total_chars' },
                    { data: 'unregistered_chars' },
                    { data: 'compliance_str' }
                ],

                columnDefs: [														
                    { "orderable": false, "targets": [ 0 ] },                
                ],

                order: [ [ 1, "asc" ] ],

                filterDropDown: {										
                    columns: [	                                                          
                        {
                            idx: 1
                        },
                        {
                            idx: 2
                        },
                        {
                            idx: 3
                        },
                        {
                            idx: 4
                        },
                        {
                            idx: 7
                        }
                    ],
                    bootstrap: true
                },
                
                createdRow: function( row, data, dataIndex ) 
                {
                    if (!data['is_compliant'])
                    {
                        $(row).addClass('danger');
                    }                
                }            
            });       
        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link href="{% static 'memberaudit/contracts.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
    
{% endblock %}