memberaudit/urls.py
from django.urls import path

from . import views

app_name = "memberaudit"

urlpatterns = [
    path("", views.index, name="index"),
    path("launcher", views.launcher, name="launcher"),
    path(
        "character_viewer/<int:character_pk>/",
        views.character_viewer,
        name="character_viewer",
    ),
    path("add_character", views.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        views.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        views.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        views.unshare_character,
        name="unshare_character",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        views.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        views.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        views.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        views.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        views.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        views.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        views.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        views.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        views.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail_data/<int:character_pk>/<int:mail_pk>/",
        views.character_mail_data,
        name="character_mail_data",
    ),
    path(
        "character_roles_data/<int:character_pk>/",
        views.character_roles_data,
        name="character_roles_data",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        views.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        views.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        views.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        views.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        views.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path("character_finder", views.character_finder, name="character_finder"),
    path(
        "character_finder_data",
        views.character_finder_data,
        name="character_finder_data",
    ),
    path("reports", views.reports, name="reports"),
    path(
        "user_compliance_report_data",
        views.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        views.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        views.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        views.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        views.character_attribute_data,
        name="character_attribute_data",
    ),
]

memberaudit/views/launcher.py
"""
views for launcher
"""

from django.contrib.auth.decorators import login_required, permission_required
from django.db import transaction
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound
from django.shortcuts import redirect, render

from allianceauth.authentication.models import CharacterOwnership
from allianceauth.eveonline.models import EveCharacter
from django.utils.html import format_html

from esi.decorators import token_required

from memberaudit import tasks
from memberaudit.models import Character
from memberaudit.utils import messages_plus
from memberaudit.views.utils import add_common_context


@login_required
@permission_required("memberaudit.basic_access")
def index(request):
    return redirect("memberaudit:launcher")


@login_required
@permission_required("memberaudit.basic_access")
def launcher(request) -> HttpResponse:
    owned_chars_query = (
        CharacterOwnership.objects.filter(user=request.user)
        .select_related(
            "character",
            "memberaudit_character",
            "memberaudit_character__wallet_balance",
            "memberaudit_character__skillpoints",
            "memberaudit_character__unread_mail_count",
        )
        .order_by()
    )
    has_auth_characters = owned_chars_query.count() > 0
    auth_characters = list()
    unregistered_chars = list()
    for character_ownership in owned_chars_query:
        eve_character = character_ownership.character
        try:
            character = character_ownership.memberaudit_character
        except AttributeError:
            unregistered_chars.append(eve_character.character_name)
        else:
            auth_characters.append(
                {
                    "character_id": eve_character.character_id,
                    "character_name": eve_character.character_name,
                    "character": character,
                    "alliance_id": eve_character.alliance_id,
                    "alliance_name": eve_character.alliance_name,
                    "corporation_id": eve_character.corporation_id,
                    "corporation_name": eve_character.corporation_name,
                }
            )

    unregistered_chars = sorted(unregistered_chars)

    try:
        main_character_id = request.user.profile.main_character.character_id
    except AttributeError:
        main_character_id = None

    context = {
        "page_title": "My Characters",
        "auth_characters": auth_characters,
        "has_auth_characters": has_auth_characters,
        "unregistered_chars": unregistered_chars,
        "has_registered_characters": len(auth_characters) > 0,
        "main_character_id": main_character_id,
    }

    """
    if has_auth_characters:
        messages_plus.warning(
            request,
            format_html(
                "Please register all your characters. "
                "You currently have <strong>{}</strong> unregistered characters.",
                unregistered_chars,
            ),
        )
    """
    return render(
        request,
        "memberaudit/launcher.html",
        add_common_context(request, context),
    )


@login_required
@permission_required("memberaudit.basic_access")
@token_required(scopes=Character.get_esi_scopes())
def add_character(request, token) -> HttpResponse:
    token_char = EveCharacter.objects.get(character_id=token.character_id)
    try:
        character_ownership = CharacterOwnership.objects.select_related(
            "character"
        ).get(user=request.user, character=token_char)
    except CharacterOwnership.DoesNotExist:
        messages_plus.error(
            request,
            format_html(
                "You can register your main or alt characters."
                "However, character <strong>{}</strong> is neither. ",
                token_char.character_name,
            ),
        )
    else:
        with transaction.atomic():
            character, _ = Character.objects.update_or_create(
                character_ownership=character_ownership
            )

        tasks.update_character.delay(character_pk=character.pk)
        messages_plus.success(
            request,
            format_html(
                "<strong>{}</strong> has been registered. "
                "Note that it can take a minute until all character data is visible.",
                character.character_ownership.character,
            ),
        )

    return redirect("memberaudit:launcher")


@login_required
@permission_required("memberaudit.basic_access")
def remove_character(request, character_pk: int) -> HttpResponse:
    try:
        character = Character.objects.select_related(
            "character_ownership__user", "character_ownership__character"
        ).get(pk=character_pk)
    except Character.DoesNotExist:
        return HttpResponseNotFound(f"Character with pk {character_pk} not found")

    character_name = character.character_ownership.character.character_name
    if character.character_ownership.user == request.user:
        character.delete()
        messages_plus.success(
            request,
            format_html(
                "Removed character <strong>{}</strong> as requested.", character_name
            ),
        )
    else:
        return HttpResponseForbidden(
            f"No permission to remove Character with pk {character_pk}"
        )

    return redirect("memberaudit:launcher")


@login_required
@permission_required("memberaudit.basic_access")
def share_character(request, character_pk: int) -> HttpResponse:
    try:
        character = Character.objects.select_related(
            "character_ownership__user", "character_ownership__character"
        ).get(pk=character_pk)
    except Character.DoesNotExist:
        return HttpResponseNotFound(f"Character with pk {character_pk} not found")

    if character.character_ownership.user == request.user:
        character.is_shared = True
        character.save()
    else:
        return HttpResponseForbidden(
            f"No permission to remove Character with pk {character_pk}"
        )

    return redirect("memberaudit:launcher")


@login_required
@permission_required("memberaudit.basic_access")
def unshare_character(request, character_pk: int) -> HttpResponse:
    try:
        character = Character.objects.select_related(
            "character_ownership__user", "character_ownership__character"
        ).get(pk=character_pk)
    except Character.DoesNotExist:
        return HttpResponseNotFound(f"Character with pk {character_pk} not found")

    if character.character_ownership.user == request.user:
        character.is_shared = False
        character.save()
    else:
        return HttpResponseForbidden(
            f"No permission to remove Character with pk {character_pk}"
        )

    return redirect("memberaudit:launcher")

memberaudit/templates/memberaudit/characters/character_main.html
{% extends 'memberaudit/characters/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

{% block details %}
<div class="panel panel-default">
    <div class="panel-body">

        <div class="rows">

            <div class="col-md-2">
                <img src="{{ auth_character|character_portrait_url:128 }}" />
            </div>

            <div class="col-md-3">
                <dl class="dl-horizontal">
                    <dt>Character</dt>
                    <dd>{{ auth_character.character_name}}</dd>
                    <dt>Corporation</dt>
                    <dd>
                        <a href="{{ auth_character.corporation_name|dotlan_corporation_url }}" target="_blank">
                            {{ auth_character.corporation_name }}
                        </a>
                    </dd>
                    <dt>Alliance</dt>
                    <dd>
                        {% if auth_character.alliance_name %}
                            <a href="{{ auth_character.alliance_name|dotlan_alliance_url }}" target="_blank">
                                {{ auth_character.alliance_name }}
                            </a>
                        {% else %}
                            -
                        {% endif %}
                    </dd>
                    <dt>Faction</dt>
                    <dd>{{ character_details.faction|default:"-" }}</dd>
                </dl>
            </div>

            <div class="col-md-3">
                <dl class="dl-horizontal">
                    <dt>Born</dt>
                    <dd>{{ character_details.birthday|naturalday }}</dd>
                    <dt>Skillpoints</dt>
                    <dd>{{ character.total_sp|intword }}</dd>
                    <dt>Wallet</dt>
                    <dd>{{ character.wallet_balance|intword }}</dd>
                    <dt>Sec. Status</dt>
                    <dd>{{ character_details.security_status|floatformat|default:"-" }}</dd>
                </dl>
            </div>

            <div class="col-md-3">
                <dl class="dl-horizontal">
                    <dt>System</dt>
                    <dd>
                        <div id="div_location">Loading...</div>
                    </dd>
                    <dt>Location</dt>
                    <dd>{{ auth_character.corporation_name }}</dd>
                    <dt>Race</dt>
                    <dd>{{ character_details.eve_bloodline.eve_race }}</dd>
                    <dt>Achestry</dt>
                    <dd>{{ character_details.eve_bloodline }}</dd>
                </dl>
            </div>

        </div>

    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation">
                    <a href="#bio" aria-controls="bio" role="tab" data-toggle="tab">Bio</a>
                </li>
                <li role="presentation">
                    <a href="#history" aria-controls="history" role="tab" data-toggle="tab">Corporation History</a>
                </li>
                <li role="presentation" class="disabled">
                    <a href="#clones" aria-controls="clones" role="tab" data-toggle="tab">Clones</a>
                </li>
                <li role="presentation">
                    <a href="#skills" aria-controls="skills" role="tab" data-toggle="tab">Skills</a>
                </li>
                <li role="presentation" class="disabled">
                    <a href="#skillqueue" aria-controls="skillqueue" role="tab" data-toggle="tab">Skillqueue</a>
                </li>
                <li role="presentation">
                    <a href="#mail" aria-controls="mail" role="tab" data-toggle="tab">
                        Mail
                    </a>
                </li>
                <li role="presentation" class="active">
                    <a href="#wallet" aria-controls="wallet" role="tab" data-toggle="tab">Wallet</a>
                </li>
                <li role="presentation" class="disabled"><a href="#contracts" aria-controls="contracts" role="tab"
                        data-toggle="tab">Contracts</a></li>
                <li role="presentation" class="disabled"><a href="#contacts" aria-controls="contacts" role="tab"
                        data-toggle="tab">Contacts</a></li>
                <li role="presentation" class="disabled"><a href="#assets" aria-controls="assets" role="tab"
                        data-toggle="tab">Assets</a></li>
            </ul>
            <br>

            <!-- Tab panes -->
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane" id="bio">
                    {{ character_details.description_plain|default:"-" }}
                </div>

                <div role="tabpanel" class="tab-pane" id="history">
                    <dl class="dl-horizontal">
                        {% for entry in corporation_history %}
                        <dt>{{ entry.corporation_html }}</dt>
                        <dd>{{ entry.start_date|naturalday }} - {{ entry.end_date|naturalday }}</dd>
                        {% endfor %}
                    </dl>
                </div>

                <div role="tabpanel" class="tab-pane" id="clones">TBD</div>

                <div role="tabpanel" class="tab-pane" id="skills">
                    <div class="table-responsive">
                        <table class="table table-striped" id="tab_skills" style="width:100%;">
                            <thead>
                                <tr>
                                    <th>Group</th>
                                    <th>Skill</th>
                                    <th>Level</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane" id="skillqueue">TBD</div>
                
                <div role="tabpanel" class="tab-pane" id="mail">
                    <div class="table-responsive">
                        <table class="table table-striped" id="tab_mails" style="width:100%;">
                            <thead>
                                <tr>                                    
                                    <th>sent</th>
                                    <th>from</th>
                                    <th>to</th>
                                    <th>subject</th>                                    
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
                
                <div role="tabpanel" class="tab-pane active" id="wallet">
                    <div class="table-responsive">
                        <table class="table" id="tab_wallet" style="width:100%;">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Type</th>
                                    <th>First party</th>
                                    <th>Second party</th>
                                    <th>Amount</th>
                                    <th>Balance</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="contracts">TBD</div>
                <div role="tabpanel" class="tab-pane" id="contacts">TBD</div>
                <div role="tabpanel" class="tab-pane" id="assets">TBD</div>
            </div>
        </div>
    </div>
</div>


{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    <script type="application/javascript"
        src="https://cdn.datatables.net/rowgroup/1.1.2/js/dataTables.rowGroup.min.js"></script>
    <script type="application/javascript">
        $(document).ready(function () {
            $("#div_location").load(
                "{% url 'memberaudit:character_location_data' character.pk %}"
            );

             $('#tab_mails').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:character_mails_data' character.pk %}",
                    dataSrc: '',
                    cache: false
                },
                columns: [                    
                    { data: 'sent' },
                    { data: 'from' },
                    { data: 'to' },
                    { data: 'subject' }      
                ],
                order: [[0, "desc"]],
            });

            $('#tab_skills').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:character_skills_data' character.pk %}",
                    dataSrc: '',
                    cache: false
                },
                columns: [
                    { data: 'group' },
                    { data: 'skill' },
                    { data: 'level' },
                ],
                order: [[0, "asc"], [1, "asc"]],
                rowGroup: {
                    dataSrc: 'group',
                    className: 'table-group'
                },
                columnDefs: [
                    { "visible": false, "targets": [0] }
                ],    
                createdRow: function( row, data, dataIndex ) 
                {
                    if (data[1]) {
                        $(row).addClass('danger');
                    }                
                }  
            });

            $('#tab_wallet').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:character_wallet_journal_data' character.pk %}",
                    dataSrc: '',
                    cache: false
                },
                columns: [
                    { data: 'date' },
                    { data: 'ref_type' },
                    { data: 'first_party' },
                    { data: 'second_party' },
                    { data: 'amount' },
                    { data: 'balance' },
                    { data: 'description' },
                ],
                order: [[0, "desc"]],
            });
        });
    </script>
{% endblock extra_javascript %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="https://cdn.datatables.net/rowgroup/1.1.2/css/rowGroup.bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/character_main.css' %}" type="text/css">
{% endblock extra_css %}

{% block extra_script %}
{% endblock extra_script %}

memberaudit/templates/memberaudit/characters/launcher.html
{% extends 'memberaudit/characters/base.html' %}
{% load i18n %}
{% load static %}

{% block details %}

<div class="panel panel-default">
    <div class="panel-heading" style="display:flex;">
        <h3 class="panel-title">{% trans 'Characters' %}</h3>
    </div>
    <div class="panel-body">
        {% if has_registered_chars %}
        <table class="table" id="tab_standingssync">
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th></th>
                    <th>Location</th>
                    <th>Registered?</th>
                </tr>
            </thead>
            <tbody>
                {% for character in characters %}
                    <tr>
                        <td class="text-center"><img class="ra-avatar img-circle" src="{{ character.portrait_url }}">
                        </td>
                        <td>{{ character.name }}</td>
                        <td>
                            {% if character.is_registered %}
                                <a class="btn btn-primary" href="{% url 'memberaudit:character_main' character.character_pk %}"
                                    role="button" title="Open character details">
                                    <i class="fas fa-search"></i>
                                </a>
                                <a class="btn btn-danger" href="{% url 'memberaudit:character_main' character.character_pk %}"
                                    role="button" title="Remove this character from the launcher">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if character.is_registered %}
                            <div id="location_{{ character.character_pk }}">
                                Loading...
                            </div>
                            {% else %}
                            Not registered
                            {% endif %}
                        </td>
                        <td>
                            <span style="font-size: 125%">
                                {% if character.is_registered %}
                                <span class="text-success"><i class="fa fa-check-circle fa-fw"></i></span>
                                {% else %}
                                <span class="text-danger"><i class="fa fa-times-circle fa-fw"></i></span>
                                {% endif %}
                            </span>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>None</p>
        {% endif %}
    </div>
</div>

<a class="btn btn-primary" href="{% url 'memberaudit:add_owner' %}">
    Register character
</a>
<p class="text-muted">By registering your character you agree that the alliance can access your data</p>

{% endblock details %}

{% block extra_javascript %}
<script>
    $(document).ready(function () {
        {% for character in characters %}
        {% if character.is_registered %}
        $("#location_" + {{ character.character_pk }}).load(
            "{% url 'memberaudit:character_location_data' character.character_pk %}"
        );
    {% endif %}
    {% endfor %}
        });
</script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

memberaudit/templates/memberaudit/characters/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}
{% load memberaudit %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'memberaudit:index' %}">
                {{ section_title }}
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'memberaudit:launcher' %}">
                    <a href="{% url 'memberaudit:launcher' %}">
                        Register
                        {%  if unregistered_count > 0 %}
                            <span class="badge">{{ unregistered_count }}</span>
                        {% endif %}
                    </a>
                </li>
                
                    {% for character in registered_characters %}
                        <li class="{% navactive_2 request 'memberaudit:character_main' character.pk %}">
                            <a href="{% url 'memberaudit:character_main' character.pk %}">
                                {{ character.name }}
                            </a>
                        </li>
                    
                    {% endfor %}
                
            </ul>
        </div>
    </div>
</nav>